### ISSUE TITLE
Derived rule IDs may be invalid

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/sigma-to-hayabusa-converter#13]
I have only checked a few rules, but it seems that the derived IDs may be invalid.

Now:
Built-in rule:
```
title: 7Zip Compressing Dump Files
id: 93586827-5f54-fc91-0b2f-338fd5365694
```

Sysmon rule:
```
title: 7Zip Compressing Dump Files
id: e02e1c15-b64d-0c08-3771-5948dfb17ed7
related:
    - id: 1ac14d38-3dfc-4635-92c7-e3fd1c5f5bfc
      type: derived
    - id: ec570e53-4c76-45a9-804d-dc3f355ff7a7
      type: derived
```

What it should be:
Built-in rule:
```
title: 7Zip Compressing Dump Files
id: e02e1c15-b64d-0c08-3771-5948dfb17ed7
related:
    - id: 93586827-5f54-fc91-0b2f-338fd5365694
      type: derived
```

Sysmon rule:
```
title: 7Zip Compressing Dump Files
id: 93586827-5f54-fc91-0b2f-338fd5365694 
```

**Comment by fukusuket** [comment]
## Expected behavior
### Sigma original
```yaml
title: 7Zip Compressing Dump Files
id: ec570e53-4c76-45a9-804d-dc3f355ff7a7
related:
    - id: 1ac14d38-3dfc-4635-92c7-e3fd1c5f5bfc
      type: derived
```

### Converted Sysmon
New UUID is assigned because `Channel`/`EventID` is added to the original Sigma rule.
```yaml
title: 7Zip Compressing Dump Files
id: e02e1c15-b64d-0c08-3771-5948dfb17ed7
related:
    - id: 1ac14d38-3dfc-4635-92c7-e3fd1c5f5bfc
      type: derived
    - id: ec570e53-4c76-45a9-804d-dc3f355ff7a7
      type: derived
```
### Converted Builtin
New UUID is assigned because `Channel`/`EventID` is added to the original Sigma rule.
```yaml
title: 7Zip Compressing Dump Files
id: 93586827-5f54-fc91-0b2f-338fd5365694
related:
    - id: 1ac14d38-3dfc-4635-92c7-e3fd1c5f5bfc
      type: derived
    - id: ec570e53-4c76-45a9-804d-dc3f355ff7a7
      type: derived
```
