### ISSUE TITLE
[bug] When ruletype=hayabusa, ruletype=sigma is added unnecessarily (correlation rule)

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/sigma-to-hayabusa-converter#28]
In the correlations rule, the ruletype is not assigned correctly as follows

original
```yml
title: User Guessing
id: 0ae09af3-f30f-47c2-a31c-83e0b918eeee
related:
    - id: 4574194d-e7ca-4356-a95c-21b753a1787e
      type: obsolete
status: test
description: Search for many 4625 failed logon attempts due to wrong usernames in a short period of time.
references: https://attack.mitre.org/techniques/T1110/003/
author: Zach Mathis
date: 2024-10-13
modified: 2024-10-13
tags:
    - attack.t1110.003
    - attack.credential_access
correlation:
    type: value_count
    rules:
        - non_existent_user
    group-by:
        - IpAddress
    timespan: 5m
    condition:
        gt: 3
        field: TargetUserName
falsepositives:
    - User mistyping username
level: medium
ruletype: Hayabusa
---
title: Failed Logon - Non-Existent User
id: b2c74582-0d44-49fe-8faa-014dcdafee62
name: non_existent_user
related:
    - id: 4574194d-e7ca-4356-a95c-21b753a1787e
      type: obsolete
status: test
description: Detects a failed logon event due to an incorrect username
#references:
author: Zach Mathis
date: 2024-10-13
modified: 2024-10-13
#tags:
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4625
        SubStatus: "0xc0000064" #Username does not exist
    condition: selection
#falsepositives:
level: informational
ruletype: Hayabusa
```

converted
```yml
title: User Guessing
id: 01e66ad5-1dbb-7d56-47de-7c2d6972fa92
related:
    - id: 4574194d-e7ca-4356-a95c-21b753a1787e
      type: obsolete
    - id: 0ae09af3-f30f-47c2-a31c-83e0b918eeee
      type: derived
status: test
description: Search for many 4625 failed logon attempts due to wrong usernames in a short period of time.
references: https://attack.mitre.org/techniques/T1110/003/
author: Zach Mathis
date: 2024-10-13
modified: 2024-10-13
tags:
    - attack.t1110.003
    - attack.credential_access
correlation:
    type: value_count
    rules:
        - non_existent_user
    group-by:
        - IpAddress
    timespan: 5m
    condition:
        gt: 3
        field: TargetUserName
falsepositives:
    - User mistyping username
level: medium
ruletype: Hayabusa
ruleType: Sigma
---
title: Failed Logon - Non-Existent User
id: faab23b4-e0a9-7974-8796-d9ae6a3830de
related:
    - id: 4574194d-e7ca-4356-a95c-21b753a1787e
      type: obsolete
    - id: b2c74582-0d44-49fe-8faa-014dcdafee62
      type: derived
name: non_existent_user
status: test
description: Detects a failed logon event due to an incorrect username
author: Zach Mathis
date: 2024-10-13
modified: 2024-10-13
logsource:
    product: windows
    service: security
detection:
    security:
        Channel: Security
    selection:
        EventID: 4625
        SubStatus: '0xc0000064' #Username does not exist
    condition: security and selection
level: informational
ruletype: Sigma
```
